name: Scraper

on:
  workflow_dispatch:
    inputs:
      Vendor:
        description: 'Vendor'
        required: true
        default: 'All'
        type: choice
        options:
          - All
          - Audi
          - BMW
          - Mercedes_Benz
          - Tesla
      Market:
        description: 'Market'
        required: true
        default: 'DE'
        type: choice
        options:
          - DE
          - US
          - FR
          - NL
          - AT
          - AU

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Github Action Setup
        uses: actions/checkout@v3
